### ISSUE TITLE
yarn bootstrap fails with invalid podfile error

### ISSUE THREAD

**Issue by zakini** [react-native-menu/menu#386]
I'm trying to get this repo set up locally so I can put together a PR, but I'm getting stuck when running `yarn bootstrap`

Steps to reproduce:
```sh
git clone git@github.com:react-native-menu/menu.git
cd menu
yarn bootstrap
```

Output from `yarn bootstrap`:
```
yarn run v1.22.18
$ yarn example && yarn && yarn pods
$ yarn --cwd example
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-native > react-native-codegen > jscodeshift@0.11.0" has unmet peer dependency "@babel/preset-env@^7.1.6".
warning "@react-native-community/eslint-config > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > react-native-test-app@0.7.5" has unmet peer dependency "@react-native-community/cli@>=4.10.0".
warning " > react-native-test-app@0.7.5" has unmet peer dependency "@react-native-community/cli-platform-android@>=4.10.0".
warning " > react-native-test-app@0.7.5" has unmet peer dependency "@react-native-community/cli-platform-ios@>=4.10.0".
[4/4] 🔨  Building fresh packages...
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-native > metro-react-native-babel-transformer@0.64.0" has unmet peer dependency "@babel/core@*".
warning "react-native > react-native-codegen > jscodeshift@0.11.0" has unmet peer dependency "@babel/preset-env@^7.1.6".
warning Workspaces can only be enabled in private projects.
[4/4] 🔨  Building fresh packages...
$ bob build
[##################################################################################################################################################################################################################################################] 2543/2543ℹ Building target commonjs
ℹ Cleaning up previous build at lib/commonjs
ℹ Compiling 5 files in src with babel
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
✔ Wrote files to lib/commonjs
ℹ Building target module
ℹ Cleaning up previous build at lib/module
ℹ Compiling 5 files in src with babel
✔ Wrote files to lib/module
ℹ Building target typescript
ℹ Cleaning up previous build at lib/typescript
ℹ Generating type definitions with tsc
✔ Wrote definition files to lib/typescript
$ cd example && pod-install --quiet
1.11.3
> pod install

[!] Invalid `Podfile` file: no implicit conversion of nil into String.

 #  from /Users/josh/Code/menu/example/ios/Podfile:7
 #  -------------------------------------------
 #
 >  use_test_app!
 #  -------------------------------------------

Aborting run
An unexpected error was encountered. Please report it as a bug:
CocoaPodsError: Command `pod install` failed.
└─ Cause: pod exited with non-zero code: 1
    at CocoaPodsPackageManager._installAsync (/Users/josh/Code/menu/node_modules/pod-install/build/index.js:2:92213)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CocoaPodsPackageManager.installAsync (/Users/josh/Code/menu/node_modules/pod-install/build/index.js:2:90176)
    at async runAsync (/Users/josh/Code/menu/node_modules/pod-install/build/index.js:2:106198)
    at async /Users/josh/Code/menu/node_modules/pod-install/build/index.js:2:106284 {
  code: 'COMMAND_FAILED',
  cause: Error: pod exited with non-zero code: 1
      at ChildProcess.h (/Users/josh/Code/menu/node_modules/pod-install/build/index.js:2:1073)
      at Object.onceWrapper (node:events:646:26)
      at ChildProcess.emit (node:events:526:28)
      at maybeClose (node:internal/child_process:1092:16)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
      ...
      at Object.spawnAsync [as default] (/Users/josh/Code/menu/node_modules/pod-install/build/index.js:2:558)
      at CocoaPodsPackageManager._runAsync (/Users/josh/Code/menu/node_modules/pod-install/build/index.js:2:92995)
      at CocoaPodsPackageManager._installAsync (/Users/josh/Code/menu/node_modules/pod-install/build/index.js:2:90499)
      at CocoaPodsPackageManager.installAsync (/Users/josh/Code/menu/node_modules/pod-install/build/index.js:2:90187)
      at runAsync (/Users/josh/Code/menu/node_modules/pod-install/build/index.js:2:106206)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async /Users/josh/Code/menu/node_modules/pod-install/build/index.js:2:106284 {
    pid: 89238,
    output: [ '', '' ],
    stdout: '',
    stderr: '',
    status: 1,
    signal: null
  },
  isPackageManagerError: true
}

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any ideas what's causing this?

**Comment by Naturalclar** [comment]
should be fixed in current main branch
